export const AUTH_CONSTANTS = {
  SESSION_TTL_HOURS: 24,
  SESSION_IDLE_TIMEOUT_HOURS: 2,

  PASSWORD_MIN_LENGTH: 8,

  BCRYPT_ROUNDS: 12,
  RESET_TOKEN_EXPIRY_HOURS: 1,

  MAX_LOGIN_ATTEMPTS: 5,
  ACCOUNT_LOCK_DURATION_MINUTES: 15,

  SESSION_COOKIE_NAME: "session_token",
} as const;
